graph TD

    comparative-analysis --> cleaning-data
    comparative-analysis --> creating-visualizations
    comparative-analysis --> exploratory-analysis
    comparative-analysis --> guided-investigation
    comparative-analysis --> hypothesis-testing
    comparative-analysis --> importing-data
    comparative-analysis --> interpreting-results
    comparative-analysis --> understanding-data
    comparative-analysis --> writing-queries
    exploratory-analysis --> cleaning-data
    exploratory-analysis --> comparative-analysis
    exploratory-analysis --> creating-visualizations
    exploratory-analysis --> guided-investigation
    exploratory-analysis --> hypothesis-testing
    exploratory-analysis --> importing-data
    exploratory-analysis --> interpreting-results
    exploratory-analysis --> understanding-data
    exploratory-analysis --> writing-queries
    guided-investigation --> cleaning-data
    guided-investigation --> creating-visualizations
    guided-investigation --> hypothesis-testing
    guided-investigation --> importing-data
    guided-investigation --> interpreting-results
    guided-investigation --> understanding-data
    guided-investigation --> writing-queries
    hypothesis-testing --> cleaning-data
    hypothesis-testing --> creating-visualizations
    hypothesis-testing --> importing-data
    hypothesis-testing --> interpreting-results
    hypothesis-testing --> understanding-data
    hypothesis-testing --> writing-queries
    presenting-data --> comparative-analysis
    presenting-data --> creating-visualizations
    presenting-data --> exploratory-analysis
    presenting-data --> guided-investigation
    presenting-data --> hypothesis-testing
    presenting-data --> interpreting-results
    marketing-experimentation --> creating-visualizations
    marketing-experimentation --> hypothesis-testing
    marketing-experimentation --> interpreting-results
    marketing-experimentation --> presenting-data
    marketing-experimentation --> qualitative-research
    cleaning-data --> detect-foreign-keys
    cleaning-data --> exploratory-analysis
    cleaning-data --> guided-investigation
    cleaning-data --> importing-data
    using-sqlite --> cleaning-data
    using-sqlite --> importing-data
    using-sqlite --> understanding-data
    using-sqlite --> writing-queries
    detect-foreign-keys --> cleaning-data
    detect-foreign-keys --> importing-data
    detect-foreign-keys --> understanding-data
    importing-data --> cleaning-data
    importing-data --> detect-foreign-keys
    importing-data --> using-sqlite
    interpreting-results --> understanding-data
    interpreting-results --> writing-queries
    qualitative-research --> hypothesis-testing
    qualitative-research --> marketing-experimentation
    writing-queries --> understanding-data
    writing-queries --> using-sqlite
    creating-visualizations --> interpreting-results
    understanding-data --> using-sqlite